### ISSUE TITLE
PR: Mime Upgrade fixes DDOS Attack Surface

### ISSUE THREAD

**Issue by frank-dspeed** [UniQLab/diet-static-middleware#5]
https://david-dm.org/UniQLab/diet-static-middleware

#4 closes that issue

**Comment by frank-dspeed** [comment]
Thanks for Accepting pull requests

**Comment by frank-dspeed** [comment]
@st235 this merge automatic sets version 1.0.1 as its a security fix don't forget please to npm release!

**Comment by st235** [comment]
@FlyOrDie I will update the repository.
UPD: @frank-dspeed updated) thanks a lot)
